name = "Raiyan Planet theme"
author = "Raiyan"
version = "1.0.0"

[theme]
name = "Tokyo Night Dark"
appearance = "dark"

[theme.style]
# Borders and surfaces
border = "#101014"
"border.variant" = "#0f0f14"
"border.focused" = "#3d59a1"
"border.selected" = "#29355a"
"border.transparent" = "#00000000"
"border.disabled" = "#363b54"

# Backgrounds
"elevated_surface.background" = "#040405"
"surface.background" = "#000000"
background = "#000000"
"element.background" = "#040405"
"element.hover" = "#13131a"
"element.active" = "#202330"
"element.selected" = "#1c1d29"
"element.disabled" = "#363b54"

# Drop targets and ghost elements
"drop_target.background" = "#1e202e80"
"ghost_element.background" = "#00000000"
"ghost_element.hover" = "#13131a"
"ghost_element.active" = "#202330"
"ghost_element.selected" = "#1c1d29"
"ghost_element.disabled" = "#363b54"

# Text colors
text = "#a9b1d6"
"text.muted" = "#787c99"
"text.placeholder" = "#646e9c"
"text.disabled" = "#545c7e"
"text.accent" = "#6183bb"

# Icons
icon = "#787c99"
"icon.muted" = "#515670"
"icon.disabled" = "#363b54"
"icon.placeholder" = "#646e9c"
"icon.accent" = "#6183bb"

# Status and title bars
"status_bar.background" = "#020202"
"title_bar.background" = "#000000"
"title_bar.inactive_background" = "#040405"

# Toolbar and tabs
"toolbar.background" = "#000000"
"tab_bar.background" = "#000000"
"tab.inactive_background" = "#000000"
"tab.active_background" = "#040405"

# Search and panels
"search.match_background" = "#3d59a166"
"panel.background" = "#040405"
"panel.focused_border" = "#3d59a1"
"pane.focused_border" = "#3d59a1"

# Scrollbars
"scrollbar.thumb.background" = "#868bc415"
"scrollbar.thumb.hover_background" = "#868bc410"
"scrollbar.thumb.border" = "#00000000"
"scrollbar.track.background" = "#00000000"
"scrollbar.track.border" = "#00000000"

# Editor
"editor.background" = "#000000"
"editor.gutter.background" = "#000000"
"editor.subheader.background" = "#040405"
"editor.active_line.background" = "#1e202e"
"editor.highlighted_line.background" = "#1e202e"
"editor.line_number" = "#363b54"
"editor.active_line_number" = "#787c99"
"editor.invisible" = "#363b54"
"editor.wrap_guide" = "#232433"
"editor.active_wrap_guide" = "#363b54"
"editor.document_highlight.read_background" = "#515c7e44"
"editor.document_highlight.write_background" = "#515c7e55"

# Terminal
"terminal.background" = "#000000"
"terminal.foreground" = "#787c99"
"terminal.bright_foreground" = "#a9b1d6"
"terminal.dim_foreground" = "#515670"

# Terminal ANSI colors
"terminal.ansi.black" = "#363b54"
"terminal.ansi.bright_black" = "#363b54"
"terminal.ansi.dim_black" = "#232433"
"terminal.ansi.red" = "#f7768e"
"terminal.ansi.bright_red" = "#f7768e"
"terminal.ansi.dim_red" = "#914c54"
"terminal.ansi.green" = "#73daca"
"terminal.ansi.bright_green" = "#73daca"
"terminal.ansi.dim_green" = "#41a6b5"
"terminal.ansi.yellow" = "#e0af68"
"terminal.ansi.bright_yellow" = "#e0af68"
"terminal.ansi.dim_yellow" = "#c49a5a"
"terminal.ansi.blue" = "#7aa2f7"
"terminal.ansi.bright_blue" = "#7aa2f7"
"terminal.ansi.dim_blue" = "#6183bb"
"terminal.ansi.magenta" = "#bb9af7"
"terminal.ansi.bright_magenta" = "#bb9af7"
"terminal.ansi.dim_magenta" = "#9d7cd8"
"terminal.ansi.cyan" = "#7dcfff"
"terminal.ansi.bright_cyan" = "#7dcfff"
"terminal.ansi.dim_cyan" = "#449dab"
"terminal.ansi.white" = "#787c99"
"terminal.ansi.bright_white" = "#acb0d0"
"terminal.ansi.dim_white" = "#515670"

# Link text
"link_text.hover" = "#7dcfff"

# Status colors
conflict = "#e0af68"
"conflict.background" = "#e0af6844"
"conflict.border" = "#e0af68"
created = "#41a6b5"
"created.background" = "#41a6b525"
"created.border" = "#41a6b5"
deleted = "#f7768e"
"deleted.background" = "#f7768e22"
"deleted.border" = "#f7768e"
error = "#db4b4b"
"error.background" = "#db4b4b22"
"error.border" = "#db4b4b"
hidden = "#515670"
"hidden.background" = "#51567044"
"hidden.border" = "#515670"
hint = "#0da0ba"
"hint.background" = "#0da0ba22"
"hint.border" = "#0da0ba"
ignored = "#515670"
"ignored.background" = "#51567044"
"ignored.border" = "#515670"
info = "#0da0ba"
"info.background" = "#0da0ba22"
"info.border" = "#0da0ba"
modified = "#6183bb"
"modified.background" = "#6183bb25"
"modified.border" = "#6183bb"
predictive = "#646e9c"
"predictive.background" = "#646e9c22"
"predictive.border" = "#646e9c"
renamed = "#449dab"
"renamed.background" = "#449dab25"
"renamed.border" = "#449dab"
success = "#41a6b5"
"success.background" = "#41a6b525"
"success.border" = "#41a6b5"
unreachable = "#515670"
"unreachable.background" = "#51567044"
"unreachable.border" = "#515670"
warning = "#e0af68"
"warning.background" = "#e0af6844"
"warning.border" = "#e0af68"

# Player colors for collaborative editing
[[theme.style.players]]
cursor = "#C678DD"
background = "#C678DD20"
selection = "#C678DD30"

[[theme.style.players]]
cursor = "#7aa2f7"
background = "#7aa2f720"
selection = "#7aa2f730"

[[theme.style.players]]
cursor = "#73daca"
background = "#73daca20"
selection = "#73daca30"

[[theme.style.players]]
cursor = "#bb9af7"
background = "#bb9af720"
selection = "#bb9af730"

[[theme.style.players]]
cursor = "#e0af68"
background = "#e0af6820"
selection = "#e0af6830"

[[theme.style.players]]
cursor = "#ff9e64"
background = "#ff9e6420"
selection = "#ff9e6430"

[[theme.style.players]]
cursor = "#f7768e"
background = "#f7768e20"
selection = "#f7768e30"

[[theme.style.players]]
cursor = "#9ece6a"
background = "#9ece6a20"
selection = "#9ece6a30"

# Syntax highlighting
[theme.style.syntax]
attribute = { color = "#bb9af7" }
boolean = { color = "#ff9e64" }
comment = { color = "#565f89", font_style = "italic" }
"comment.doc" = { color = "#565f89", font_style = "italic" }
constant = { color = "#ff9e64" }
constructor = { color = "#7dcfff" }
embedded = { color = "#a9b1d6" }
emphasis = { color = "#7aa2f7", font_style = "italic" }
"emphasis.strong" = { color = "#7aa2f7", font_weight = 700 }
enum = { color = "#7dcfff" }
function = { color = "#7aa2f7" }
hint = { color = "#0da0ba", font_weight = 700 }
keyword = { color = "#9d7cd8" }
label = { color = "#7aa2f7" }
link_text = { color = "#7dcfff", font_style = "italic" }
link_uri = { color = "#73daca" }
number = { color = "#ff9e64" }
operator = { color = "#89ddff" }
predictive = { color = "#646e9c", font_style = "italic" }
preproc = { color = "#a9b1d6" }
primary = { color = "#a9b1d6" }
property = { color = "#7dcfff" }
punctuation = { color = "#9abdf5" }
"punctuation.bracket" = { color = "#9abdf5" }
"punctuation.delimiter" = { color = "#9abdf5" }
"punctuation.list_marker" = { color = "#7dcfff" }
"punctuation.special" = { color = "#89ddff" }
string = { color = "#9ece6a" }
"string.escape" = { color = "#bb9af7" }
"string.regex" = { color = "#b4f9f8" }
"string.special" = { color = "#bb9af7" }
"string.special.symbol" = { color = "#bb9af7" }
tag = { color = "#f7768e" }
"text.literal" = { color = "#9ece6a" }
title = { color = "#7dcfff", font_weight = 600 }
type = { color = "#7dcfff" }
variable = { color = "#a9b1d6" }
"variable.special" = { color = "#f7768e" }
variant = { color = "#7dcfff" }